In [2]:
import pandas as pd
import numpy as np

In [4]:
s1 = pd.Series([4,7,-5,3]) #创建一个series,索引为默认值
print(s1)

0    4
1    7
2   -5
3    3
dtype: int64


In [5]:
s1.values

array([ 4,  7, -5,  3])

In [6]:
s1.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
s2 = pd.Series([4,56,5,3,2], index = ['a', 'b','c','d','e'])

In [8]:
print(s2)

a     4
b    56
c     5
d     3
e     2
dtype: int64


In [9]:
s2.value_counts

<bound method IndexOpsMixin.value_counts of a     4
b    56
c     5
d     3
e     2
dtype: int64>

In [10]:
s2.values

array([ 4, 56,  5,  3,  2])

In [11]:
#Series可以看成一个定长的有序字典
dic1 = {'apple':5, 'pen':3, 'applepen':10}
s3 = pd.Series(dic1)
print(s3)

apple        5
pen          3
applepen    10
dtype: int64


In [13]:
#DataFrame
data = {'year':[2016,2017,2018,2019],
        'income':[10000,20000,30000,40000],
        'pay':[5000,20000,3000,300000]
       }
df1 = pd.DataFrame(data)
df1

year  income     pay
0  2016   10000    5000
1  2017   20000   20000
2  2018   30000    3000
3  2019   40000  300000

In [14]:
df2 = pd.DataFrame(np.arange(12).reshape((3,4)))

In [15]:
df2

0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [17]:
df3 = pd.DataFrame(np.arange(12).reshape((3,4)), index = ['a', 'b', 'c'], columns = [2,3,4,5])
df3

2  3   4   5
a  0  1   2   3
b  4  5   6   7
c  8  9  10  11

In [18]:
df3.index

Index(['a', 'b', 'c'], dtype='object')

In [20]:
df3.values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
df3.describe()

2    3     4     5
count  3.0  3.0   3.0   3.0
mean   4.0  5.0   6.0   7.0
std    4.0  4.0   4.0   4.0
min    0.0  1.0   2.0   3.0
25%    2.0  3.0   4.0   5.0
50%    4.0  5.0   6.0   7.0
75%    6.0  7.0   8.0   9.0
max    8.0  9.0  10.0  11.0

In [23]:
df1.T

0      1      2       3
year     2016   2017   2018    2019
income  10000  20000  30000   40000
pay      5000  20000   3000  300000

In [24]:
df1.describe()

year        income            pay
count     4.000000      4.000000       4.000000
mean   2017.500000  25000.000000   82000.000000
std       1.290994  12909.944487  145531.210856
min    2016.000000  10000.000000    3000.000000
25%    2016.750000  17500.000000    4500.000000
50%    2017.500000  25000.000000   12500.000000
75%    2018.250000  32500.000000   90000.000000
max    2019.000000  40000.000000  300000.000000

In [25]:
df3.sort_index(axis = 0) #行排序

2  3   4   5
a  0  1   2   3
b  4  5   6   7
c  8  9  10  11

In [26]:
df3.sort_index(axis = 1) #列排序

2  3   4   5
a  0  1   2   3
b  4  5   6   7
c  8  9  10  11

In [29]:
df3.sort_values(by = 3)

2  3   4   5
a  0  1   2   3
b  4  5   6   7
c  8  9  10  11

In [30]:
#总体来说，Series相当于数组numpy.array类似，有默认索引或者自定义索引；DataFrame相当于有表格，有行表头和列表头