In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3])

In [3]:
arr2 = arr1 #共享一块内存（指针指向同一块内存，就是浅拷贝）

In [4]:
arr2[0] = 5

In [5]:
print(arr1)
print(arr2)

[5 2 3]
[5 2 3]


In [6]:
arr3 = arr1.copy() #深拷贝

In [7]:
arr3[0] = 10
print(arr1)
print(arr3)

[5 2 3]
[10  2  3]


In [13]:
arr4 = arr1[np.newaxis,:]
print(arr4,arr4.shape)

[[5 2 3]] (1, 3)


In [14]:
arr4[0]

array([5, 2, 3])

In [15]:
arr5 = arr4

In [16]:
arr5[0] = 199

In [17]:
print(arr5)
print(arr4)

[[199 199 199]]
[[199 199 199]]


In [18]:
arr5[0][0] = 10

In [19]:
print(arr5)
print(arr4)

[[ 10 199 199]]
[[ 10 199 199]]


In [20]:
arr5 = arr4.copy()

In [21]:
print(arr5)
print(arr4)

[[ 10 199 199]]
[[ 10 199 199]]


In [22]:
arr5[0][0] = 100

In [23]:
print(arr5)
print(arr4)

[[100 199 199]]
[[ 10 199 199]]
